name: Generate contribution animations

on:
  schedule:
    - cron: "0 */12 * * *"  # Setiap 12 jam
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10

    steps:
      - name: Generate Pacman graph
        uses: Platane/snk@v3
        with:
          github_user_name: Zharif-1135
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Generate Snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Zharif-1135
          outputs: |
            ./output/snake/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
